### ISSUE TITLE
Pairwise doesn't work with custom distance metrics

### ISSUE THREAD

**Issue by EssamWisam** [JuliaStats/Distances.jl#255] opened 2023-08-24 11:09 UTC
```julia
using Distances


struct MyMetric <: Metric end

function Distances.evaluate(dist::MyMetric,a::AbstractVector,b::AbstractVector)
    sum(abs.(a - b))
end

m = MyMetric()
Distances.evaluate(m, [9,2,3], [1,5,3])

X = rand(5, 5)

pairwise(m, X, X)
```
This throws
```
MethodError: objects of type MyMetric are not callable
```

**Comment by dkarrasch** [comment] 2023-09-03 09:57
Instead of `evaluate`, you need to define

```julia
(::MyMetric)(a::AbstractVector, b::AbstractVector)
    sum(abs.(a - b))
end
```

We should perhaps document clearly what exactly is needed for custom metrics.

**Comment by alior101** [comment] 2023-10-10 15:55
Hi,
@dkarrasch  - running your code gives:


```
struct MyMetric <: Metric end
(::MyMetric)(a::AbstractVector, b::AbstractVector); sum(abs.(a - b))

```
`ERROR: syntax: invalid "::" syntax around...`

**Comment by alior101** [comment] 2023-10-10 15:59
Please ignore the previous post 
ok - adding the "function" before that line fixed it ...

**Comment by dkarrasch** [comment] 2023-10-10 18:02
True, sorry for the confusion.

**Comment by KwatMDPhD** [comment] 2024-02-03 04:54
Duplicate of #257, which is fixed and should be closed :)

**Closed** 2024-02-03 06:57 UTC
